/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (

create database vet_clinic;
create table animals(
    id int primary key generated by default as identity, 
    name varchar(100), date_of_birth date, escape_attempts int, 
    neutered boolean, weight_in_kg decimal(5,2));

 alter table animals add species varchar(100);
