 CREATE SCHEMA clinic;
 CREATE TABLE medical_histories(id int generated by default as identity primary key, admitted_at date,patient_id int, status varchar(50),	patient_id INTEGER REFERENCES patients(id),);
 CREATE TABLE treatments(id int generated by default as identity primary key, type varchar(100), name varchar(50));
 CREATE TABLE invoice_items(id int generated by default as identity primary key,unit_price DECIMAL(5,2),quantity int, total_price DECIMAL(5,2), invoice_id int, treatment_id int,invoice_id INTEGER REFERENCES invoices(id),
	treatment_id INTEGER REFERENCES treatments(id));
 CREATE TABLE invoices(id int generated by default as identity primary key, total_amount DECIMAL(5,2), generated_at date, payed_at date, medical_history_id int,	medical_history_id INTEGER REFERENCES medical_histories(id));
 CREATE TABLE patients(id int generated by default as identity primary key, name varchar(100), date_of_birth date);

-- Add join table 
CREATE TABLE treatments_medical_histories(treatment_id int REFERENCES treatments(id), medical_id int REFERENCES medical_histories(id),)

-- Add relationships 
ALTER TABLE medical_histories ADD CONSTRAINT fk_medical_histories FOREIGN KEY (customer_id) REFERENCES customers (id);