/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (

create database vet_clinic;
create table animals(
    id int primary key generated by default as identity, 
    name varchar(100), date_of_birth date, escape_attempts int, 
    neutered boolean, weight_in_kg decimal(5,2));

 alter table animals add species varchar(100);

 CREATE TABLE owners(id int generated by default as identity primary key not null, full_name varchar(100), age int);
 CREATE TABLE species (id int generated by default as identity primary key not null, name varchar(100));

 alter table animals add foreign key (species_id) references species;
 alter table animals add foreign key (owner_id) references owners;

 CREATE TABLE vets (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80),
	age int,
	date_of_graduation date);
    CREATE TABLE specializations (
	vet_id INTEGER REFERENCES vets(id),
	species_id INTEGER REFERENCES species(id)
);

create table visits (vet_id int references vets(id),animal_id int references animals(id),date_of_visit date;
);

